blank_issues_enabled: true
contact_links:
  - name: ScribbleLab Comunity
    url: https://discord.gg/Y9SmAGfJMR
    about: Please ask and answer questions here.
  - name: ScribbleLabApp support
    email: n3v1010@gmail.com
    about: support email
