name: 🧨 Crash Report
description: Something is not working as expected.
title: "[Crash]: <description>"
labels: "P3", "type: crash", "needs review"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this crash report! I'd also be very helpful if you answer the questions [here](https://forms.gle/gafqXx9MHRFUhmge7).
  - type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what happened before, while and after the crash.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version
      placeholder: >-
        Please tell us which version you're using. Follow our Guide under Settings -> Info and Settings -> Help
         - SL_Build sha [e.g. 15a240d]
         - SL_Build number [e.g. 1]
         - SL_Langauge [e.g. en]
         - SL_Version Number [e.g. 0.0.1-alpha]
         - iOS version [e.g. 17.0.3]
         - iPadOS version [e.g. 17.0.3]
         - macOS version [e.g. 14.0]
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reliably reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      placeholder: >-
        Any other context or considerations about the bug...

  - type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        If applicable, please provide relevant screenshots or screen recordings...

  - type: checkboxes
    id: new-crash
    attributes:
      label: Is there an existing crash report for this?
      description: Please search to see if an issue already exists for the crash you encountered.
      options:
        - label: I have searched the existing issues
          required: true
