name: ✨ Feature request
description: Suggest an idea for this project
title: "[Feature]: <description>"
labels: "type: feature", "needs review", "help wanted"

body:
  - type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what you would like to happen...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      placeholder: >-
        Any alternative solutions or features you've considered...

  - type: textarea
    attributes:
      label: Additional Context
      placeholder: >-
        Any other context or considerations about the feature request...

  - type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        If applicable, please provide relevant screenshots or screen recordings...

  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you encountered.
      options:
        - label: I have searched the existing issues
          required: true
