name: Autoresponder

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, Thank you for reporting this issue - Our maintainers and interns will soon respond. To make communication even better join our Discord Community [here](https://discord.gg/Y5mUJbNC8h)."
        pr-message: "Hi there, Thank you for creating this PR - Our maintainers and interns will soon respond. To make communication even better join our Discord Community [here](https://discord.gg/Y5mUJbNC8h)."
