name: Build & Test ScribbleLab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        os: [macOS, iOS]
        configuration: [Alpha, Beta, Debug, Release]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_16.app/Contents/Developer

      - name: Build project using Matrix build system
        run: |
          if [ "${{ matrix.os }}" == "iOS" ]; then
            xcodebuild -scheme ScribbleLab -configuration ${{ matrix.configuration }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
          else
            xcodebuild -scheme ScribbleLab -configuration ${{ matrix.configuration }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
          fi

      - name: Run Tests
        run: |
          if [ "${{ matrix.os }}" == "iOS" ]; then
            xcodebuild test -scheme ScribbleLab -configuration ${{ matrix.configuration }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          else
            xcodebuild test -scheme ScribbleLab -configuration ${{ matrix.configuration }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          fi
