name: Linting ScribbleLab

on:
 push:
    branches: ["main"]
 pull_request:
    branches: ["main"]
jobs:
  SwiftLint:
    runs-on: macOS-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Install SwiftLint
         run: brew install swiftlint
       - name: Run SwiftLint
         run: swiftlint --strict