name: Update Swift Dependencies

on:
  pull_request:
    paths:
      - '.github/workflows/update-dependencies.yml'

jobs:
  update-dependencies:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        xcodebuild -resolvePackageDependencies
        swift package update

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update dependencies"
        git push